[theme]
base = "light"
primaryColor = "#E4F6B3"
backgroundColor = "#E4F6B3"
secondaryBackgroundColor = "#E4F6B3"
textColor = "#000000"
linkColor = "#000000"
borderColor = "#009f13"
showWidgetBorder = true
buttonRadius = "10px"
baseRadius = "12px"

[theme.sidebar]
backgroundColor = "#E4F6B3"
secondaryBackgroundColor = "#E4F6B3"
textColor = "#000000"
primaryColor = "#E4F6B3"